---
kind: Secret
apiVersion: v1
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud.conf: CltHbG9iYWxdCmF1dGgtdXJsPWh0dHA6Ly8xOTIuMTY4Ljg4LjI1MDozNTM1Ny92Mwp1c2VybmFtZT1sYi1hZG1pbgpwYXNzd29yZD1yb290MTIzCnJlZ2lvbj1SZWdpb25PbmUKdGVuYW50LW5hbWU9YWRtaW4KZG9tYWluLW5hbWU9RGVmYXVsdAp1c2VyLWRvbWFpbi1uYW1lPURlZmF1bHQKdGxzLWluc2VjdXJlPXRydWUKCltMb2FkQmFsYW5jZXJdCnVzZS1vY3RhdmlhPXRydWUKZmxvYXRpbmctbmV0d29yay1pZD02Yjg0Yzk2OS1lMGUxLTQxMDYtYTVkMC1hNjAxZjkyZjI5MDMKc3VibmV0LWlkPWIzODYxZWVjLWQwMTctNDI3Ny05NjliLTI1OGM5YTlkZWJmOCAKbGItcHJvdmlkZXI9YW1waG9yYSAKCltCbG9ja1N0b3JhZ2VdCmJzLXZlcnNpb249djIKCiNbS2V5TWFuYWdlcl0KI2tleS1pZCA9IGZkZmU5NmNjLTA0MDgtNGUyYi04ZDk1LTc1MzFlNGUwZTY0NwoK
